development:
  adapter: postgresql
  database: teamplayer_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: teamplayer_test
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: teamplayer_production
  pool: 5
  timeout: 5000
